// <auto-generated />
namespace GenerateCouponCapstone2022.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createrestaurantentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createrestaurantentity));
        
        string IMigrationMetadata.Id
        {
            get { return "202205151911210_createrestaurantentity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
