// <auto-generated />
namespace GenerateCouponCapstone2022.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatecoupontable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecoupontable));
        
        string IMigrationMetadata.Id
        {
            get { return "202206011737477_updatecoupontable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
