// <auto-generated />
namespace GenerateCouponCapstone2022.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addeddatavalidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeddatavalidation));
        
        string IMigrationMetadata.Id
        {
            get { return "202206040313001_addeddatavalidation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
